language: node_js
node_js: '10'
cache: yarn
script:
- yarn ci
deploy:
  provider: npm
  skip_cleanup: true
  email: rishabhsrao@gmail.com
  on:
    tags: true
  api_key:
    # Secure token generated and added using:
    #     $ travis encrypt --com {{raw NPM token}} --add 'deploy.api_key'
    # See https://docs.travis-ci.com/user/deployment/npm/#npm-auth-token
    secure: h1O9wpHJFI0YtiBUXa36CD76VVIHswjygmMm7oSuKrk+Q/34AY185oQ44bYWKE1NY1E8477hI55CRcfZR6KZYkf6w1JB/OQaG6l4KYlixED8Oe1I/hKGDhplo06IcXi9atobEc+GiQexmBIaMcC6VbQz7PY9jZDDVzdPA6W9Vmy2JmJfTUWTxFhFNJIJNqnO318lZyKGU4yzF7yTzx6XJa/cYX75RbMLqHVatbWa+9k+vjU99yzVxcYx+V8kw1hLRJ+lqPukU99tAsuraWJ7Npz6XJoRg8+0Qj1K5RfwerwxgdmgXCXjw2nK45CL4fGtWLQiI9j/yMuH+wiRuTJpvPjY3uhsVV5PATwoRPeZcHraUachG2UcLX7Xl8VBPPsJlT/Kb0CXpTC4hI7Jsv+mlv0dC3yWanZJyVpCQG6qqYQLuHFX6et3UgXcXiErrHBPAxR4/LdwTCQ+9KHoXZcPydVo5DKqLc379L8oAi/c3/wVKXtzeseAxg5FkQ6dVO4jIvzuNj5gIVfsz48qVdRSxYnKrOQVozqK2SHrwAXza2dpCvW28kQQ/s7AvSZVZ/rA+4EY74Dnp0nR7s9/EiszLfnV7LEv1cJgwzvyKejWrqd0ltDpZLvqwFjTzdq1MdBgft3O2P9At5y/E8UikHsqWb9DRtUiayPRqnYZ+BwgFU4=
